import { useState } from 'react';
import CreditTypeSelect from './CreditTypeSelect';

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });

export default function CreditForm({ onSubmit, loading }) {
	const [form, setForm] = useState({ creditTypeId: '', amount: '', months: '', method: 'French' }); const [type, setType] = useState(null); const [error, setError] = useState('');
	const changeType = (creditTypeId, selected) => { setForm({ ...form, creditTypeId }); setType(selected); };
	const submit = (event) => { event.preventDefault(); setError(''); if (!form.creditTypeId || Number(form.amount) <= 0 || Number(form.months) <= 0) { setError('Completa todos los campos con valores válidos.'); return; } if (type && Number(form.amount) > type.maxAmount) { setError(`El monto máximo para este producto es ${type.maxAmount}.`); return; } if (type && Number(form.months) > type.maxMonths) { setError(`El plazo máximo para este producto es ${type.maxMonths} meses.`); return; } onSubmit({ ...form, creditTypeId: Number(form.creditTypeId), amount: Number(form.amount), months: Number(form.months) }); };
	return <form className="credit-form" onSubmit={submit}><CreditTypeSelect value={form.creditTypeId} onChange={changeType} /><div className="form-grid"><label>Monto<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} />{type && <small>Rango: {money.format(type.minAmount)} - {money.format(type.maxAmount)}</small>}</label><label>Plazo (meses)<input required type="number" min="1" value={form.months} onChange={(e) => setForm({ ...form, months: e.target.value })} />{type && <small>Máximo: {type.maxMonths} meses</small>}</label></div><fieldset><legend>Método de amortización</legend><label className="radio"><input type="radio" checked={form.method === 'French'} onChange={() => setForm({ ...form, method: 'French' })} /> Francés <small>cuota fija</small></label><label className="radio"><input type="radio" checked={form.method === 'German'} onChange={() => setForm({ ...form, method: 'German' })} /> Alemán <small>capital constante</small></label></fieldset>{error && <p className="message error">{error}</p>}<button className="button primary" disabled={loading}>{loading ? 'Calculando...' : 'Calcular simulación'}</button></form>;
}
